import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dkyc%26oq%3Dkyc%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBBzgzMmowajGoAgCwAgE%26sourceid%3Dchrome%26ie%3DUTF-8%26sei%3DhzwgabH7D6qdseMP-dS-2AE&q=EgRn68YaGIf5gMkGIjAooToR7qDyVEEDqfwaRv_XbGN1WxqBkVLi2PUGr22aVP69nUMR5ivcY8fptYlxUw4yAVJaAUM');
  await page.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dfacebook%26oq%3Dfacebook%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCDI0MjBqMGoxqAIAsAIA%26sourceid%3Dchrome%26ie%3DUTF-8%26sei%3DkTwgaZC9LLmwwcsP7I2vwQM&q=EgRn68YaGJL5gMkGIjAMtl8jtf2dlTJbkC56TwuWADjYMK2j4reADUKN4wgcRYRMCJObOnV3rdGNDTXP6w4yAVJaAUM');
  await page.locator('iframe[name="a-mi2b1w28fi7x"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="3"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="15"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-mi2b1w28fi7x"]').contentFrame().getByRole('button', { name: 'Next' }).click();
});